fix: fix RBS::ParsingError on multiple devise mappings
```
  1) RbsDevise::Devise.generate When devise mapping has multiple definitions generates RBS
     Failure/Error: parsed = RBS::Parser.parse_signature(rbs)

     RBS::ParsingError:
       a.rbs:40:29...40:36: Syntax error: unexpected token for method type, token=`Account` (tUIDENT)
     # ./lib/rbs_devise/devise.rb:37:in `format'
     # ./lib/rbs_devise/devise.rb:20:in `generate'
     # ./lib/rbs_devise/devise.rb:15:in `generate'
     # ./spec/rbs_devise/devise_spec.rb:30:in `block (3 levels) in <top (required)>'
     # ./spec/rbs_devise/devise_spec.rb:105:in `block (4 levels) in <top (required)>'
```